# Generated by Django 4.1.7 on 2023-03-10 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_board_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
